pipeline {
    agent any

    environment {
        DOTNET_HOME = tool name: 'dotnet-sdk', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/G1u2r3/Jenkinsfile.git' // Replace with your repository URL
            }
        }
        stage('Restore') {
            steps {
                script {
                    withEnv(["PATH+DOTNET=${DOTNET_HOME}/bin"]) {
                        bat 'dotnet restore'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    withEnv(["PATH+DOTNET=${DOTNET_HOME}/bin"]) {
                        bat 'dotnet build --configuration Release'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    withEnv(["PATH+DOTNET=${DOTNET_HOME}/bin"]) {
                        bat 'dotnet test'
                    }
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    withEnv(["PATH+DOTNET=${DOTNET_HOME}/bin"]) {
                        bat 'dotnet publish --configuration Release --output ./publish'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Example: Copy files to the deployment directory using xcopy
                    bat 'xcopy /E /I /Y ./publish \\path\\to\\deploy'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/publish/**'
            junit '**/TestResults/*.xml'
        }
    }
}
